"""
Unit tests generated from exported configuration files.
Auto-generated by generate_tests_from_configs.py
"""

import pytest
from llm_configs import ALL_MODELS
from inference_performance import (
    InferencePerformance, SystemConstraints, ParallelismConfig, ParallelismType
)


def test_llama_4_scout_decode_tensor_parallel_2gpu():
    """
    Test llama-4-scout Decode calculation with TENSOR_PARALLEL parallelism.
    
    Configuration:
    - Batch Size: 8
    - Prefill Length: 2048
    - Output Length: 8192
    - Memory: 256 GB
    - Compute: 450000 TFLOPS
    - Memory BW: 8000000 GB/s
    - Network BW: 600 GB/s
    
    Expected Results:
    - Total Time: 107.37 ms
    - TPS: 76293.95
    - Primary Bottleneck: Network Bandwidth
    - Network BW Used: 600.00 GB/s
    """
    # Load model
    model = ALL_MODELS['llama-4-scout']
    perf = InferencePerformance(model)

    # System constraints
    gpu = SystemConstraints(
        memory_capacity=256e9,
        memory_bandwidth=8000000e9,
        compute_throughput=450000e12,
        network_bandwidth=600e9
    )

    # Parallelism config
    parallel_config = ParallelismConfig(
        parallelism_type=ParallelismType.TENSOR_PARALLEL,
        tensor_parallel_size=2,
        pipeline_parallel_size=1
    )

    # Run Decode calculation
    result = perf.calculate_decode_performance(
        system_constraints=gpu,
        batch_size=8,
        prefill_length=2048,
        output_length=8192,
        parallelism_config=parallel_config,
        kernel_launch_latency=0e-6,
        return_step_details=True
    )

    # Calculate network bandwidth from step details
    total_network_traffic = sum(step.network_traffic for step in result.step_details)
    total_bottleneck_time = sum(max(step.compute_time, step.memory_bw_time, step.network_time)
                                 for step in result.step_details)
    network_bw_gbps = (total_network_traffic / total_bottleneck_time) / 1e9 if total_bottleneck_time > 0 else 0.0

    # Assertions
    assert abs(result.total_decode_time * 1000 - 107.3742) < 1.0, 'Total time mismatch'
    assert abs(result.tokens_per_second_per_user - 76293.95) < 10.0, 'TPS mismatch'
    assert result.primary_bottleneck == 'Network Bandwidth', 'Primary bottleneck mismatch'
    assert abs(result.avg_compute_utilization - 0.015028) < 0.01, 'Compute utilization mismatch'
    assert abs(result.avg_network_bw_utilization - 1.000000) < 0.01, 'Network utilization mismatch'
    assert abs(network_bw_gbps - 600.0000) < 1.0, 'Network BW used mismatch'

